[2024-12-29 21:12:27 +0530] [82489] [INFO] Starting gunicorn 23.0.0
[2024-12-29 21:12:27 +0530] [82489] [INFO] Listening at: http://0.0.0.0:8000 (82489)
[2024-12-29 21:12:27 +0530] [82489] [INFO] Using worker: sync
[2024-12-29 21:12:27 +0530] [82493] [INFO] Booting worker with pid: 82493
[2024-12-29 21:12:27 +0530] [82494] [INFO] Booting worker with pid: 82494
[2024-12-29 21:12:27 +0530] [82506] [INFO] Booting worker with pid: 82506
[2024-12-29 21:12:27 +0530] [82518] [INFO] Booting worker with pid: 82518
[2024-12-29 21:12:27 +0530] [82519] [INFO] Booting worker with pid: 82519
[2024-12-29 21:12:27 +0530] [82531] [INFO] Booting worker with pid: 82531
[2024-12-29 21:12:27 +0530] [82543] [INFO] Booting worker with pid: 82543
[2024-12-29 21:12:27 +0530] [82544] [INFO] Booting worker with pid: 82544
[2024-12-29 21:12:28 +0530] [82556] [INFO] Booting worker with pid: 82556
[2024-12-29 21:12:28 +0530] [82568] [INFO] Booting worker with pid: 82568
[2024-12-29 21:13:36 +0530] [82493] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:36 +0530] [82493] [INFO] Worker exiting (pid: 82493)
[2024-12-29 21:13:36 +0530] [82494] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:36 +0530] [82494] [INFO] Worker exiting (pid: 82494)
[2024-12-29 21:13:36 +0530] [83084] [INFO] Booting worker with pid: 83084
[2024-12-29 21:13:36 +0530] [83085] [INFO] Booting worker with pid: 83085
[2024-12-29 21:13:36 +0530] [82506] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:36 +0530] [82506] [INFO] Worker exiting (pid: 82506)
[2024-12-29 21:13:36 +0530] [82518] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:36 +0530] [82518] [INFO] Worker exiting (pid: 82518)
[2024-12-29 21:13:36 +0530] [83110] [INFO] Booting worker with pid: 83110
[2024-12-29 21:13:36 +0530] [82531] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:36 +0530] [82519] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:36 +0530] [82531] [INFO] Worker exiting (pid: 82531)
[2024-12-29 21:13:36 +0530] [82519] [INFO] Worker exiting (pid: 82519)
[2024-12-29 21:13:36 +0530] [82556] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:36 +0530] [82556] [INFO] Worker exiting (pid: 82556)
[2024-12-29 21:13:37 +0530] [82543] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:37 +0530] [82543] [INFO] Worker exiting (pid: 82543)
[2024-12-29 21:13:37 +0530] [82544] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:37 +0530] [82544] [INFO] Worker exiting (pid: 82544)
[2024-12-29 21:13:37 +0530] [82568] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:13:37 +0530] [82568] [INFO] Worker exiting (pid: 82568)
[2024-12-29 21:13:37 +0530] [83129] [INFO] Booting worker with pid: 83129
[2024-12-29 21:13:37 +0530] [83130] [INFO] Booting worker with pid: 83130
[2024-12-29 21:13:37 +0530] [83142] [INFO] Booting worker with pid: 83142
[2024-12-29 21:13:37 +0530] [83144] [INFO] Booting worker with pid: 83144
[2024-12-29 21:13:37 +0530] [83156] [INFO] Booting worker with pid: 83156
[2024-12-29 21:13:37 +0530] [83157] [INFO] Booting worker with pid: 83157
[2024-12-29 21:13:37 +0530] [83181] [INFO] Booting worker with pid: 83181
[2024-12-29 21:14:20 +0530] [83110] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83110] [INFO] Worker exiting (pid: 83110)
[2024-12-29 21:14:20 +0530] [83129] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83129] [INFO] Worker exiting (pid: 83129)
[2024-12-29 21:14:20 +0530] [83293] [INFO] Booting worker with pid: 83293
[2024-12-29 21:14:20 +0530] [83156] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83156] [INFO] Worker exiting (pid: 83156)
[2024-12-29 21:14:20 +0530] [83295] [INFO] Booting worker with pid: 83295
[2024-12-29 21:14:20 +0530] [83130] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83130] [INFO] Worker exiting (pid: 83130)
[2024-12-29 21:14:20 +0530] [83293] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83144] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83142] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83144] [INFO] Worker exiting (pid: 83144)
[2024-12-29 21:14:20 +0530] [83142] [INFO] Worker exiting (pid: 83142)
[2024-12-29 21:14:20 +0530] [83295] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83181] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83181] [INFO] Worker exiting (pid: 83181)
[2024-12-29 21:14:20 +0530] [83084] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83084] [INFO] Worker exiting (pid: 83084)
[2024-12-29 21:14:20 +0530] [83303] [INFO] Booting worker with pid: 83303
[2024-12-29 21:14:20 +0530] [83157] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83157] [INFO] Worker exiting (pid: 83157)
[2024-12-29 21:14:20 +0530] [83305] [INFO] Booting worker with pid: 83305
[2024-12-29 21:14:20 +0530] [83306] [INFO] Booting worker with pid: 83306
[2024-12-29 21:14:20 +0530] [83307] [INFO] Booting worker with pid: 83307
[2024-12-29 21:14:20 +0530] [83303] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83085] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:20 +0530] [83085] [INFO] Worker exiting (pid: 83085)
[2024-12-29 21:14:20 +0530] [83305] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83311] [INFO] Booting worker with pid: 83311
[2024-12-29 21:14:20 +0530] [83306] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83307] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83314] [INFO] Booting worker with pid: 83314
[2024-12-29 21:14:20 +0530] [83311] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83314] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:20 +0530] [83322] [INFO] Booting worker with pid: 83322
[2024-12-29 21:14:20 +0530] [83323] [INFO] Booting worker with pid: 83323
[2024-12-29 21:14:20 +0530] [83322] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:21 +0530] [83323] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:21 +0530] [83293] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:21 +0530] [83293] [INFO] Worker exiting (pid: 83293)
[2024-12-29 21:14:21 +0530] [83326] [INFO] Booting worker with pid: 83326
[2024-12-29 21:14:21 +0530] [83295] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:21 +0530] [83295] [INFO] Worker exiting (pid: 83295)
[2024-12-29 21:14:21 +0530] [83327] [INFO] Booting worker with pid: 83327
[2024-12-29 21:14:21 +0530] [83326] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:21 +0530] [83327] [ERROR] name 'requests_log' is used prior to global declaration (rate_limiter.py, line 53)
Traceback (most recent call last):
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ~~~~~~~~~~~~~~~~~^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/webs_venv/lib/python3.13/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/main.py", line 3, in <module>
    from rate_limiter import log_request, limit_rate
  File "/home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py", line 53
    global requests_log
    ^^^^^^^^^^^^^^^^^^^
SyntaxError: name 'requests_log' is used prior to global declaration
[2024-12-29 21:14:45 +0530] [83305] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:45 +0530] [83305] [INFO] Worker exiting (pid: 83305)
[2024-12-29 21:14:45 +0530] [83306] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:45 +0530] [83306] [INFO] Worker exiting (pid: 83306)
[2024-12-29 21:14:45 +0530] [83415] [INFO] Booting worker with pid: 83415
[2024-12-29 21:14:45 +0530] [83307] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:45 +0530] [83307] [INFO] Worker exiting (pid: 83307)
[2024-12-29 21:14:45 +0530] [83311] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:45 +0530] [83311] [INFO] Worker exiting (pid: 83311)
[2024-12-29 21:14:45 +0530] [83427] [INFO] Booting worker with pid: 83427
[2024-12-29 21:14:45 +0530] [83314] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:45 +0530] [83314] [INFO] Worker exiting (pid: 83314)
[2024-12-29 21:14:45 +0530] [83428] [INFO] Booting worker with pid: 83428
[2024-12-29 21:14:46 +0530] [83430] [INFO] Booting worker with pid: 83430
[2024-12-29 21:14:46 +0530] [83322] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:46 +0530] [83322] [INFO] Worker exiting (pid: 83322)
[2024-12-29 21:14:46 +0530] [83431] [INFO] Booting worker with pid: 83431
[2024-12-29 21:14:46 +0530] [83323] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:46 +0530] [83323] [INFO] Worker exiting (pid: 83323)
[2024-12-29 21:14:46 +0530] [83454] [INFO] Booting worker with pid: 83454
[2024-12-29 21:14:46 +0530] [83467] [INFO] Booting worker with pid: 83467
[2024-12-29 21:14:46 +0530] [83326] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:46 +0530] [83326] [INFO] Worker exiting (pid: 83326)
[2024-12-29 21:14:46 +0530] [83327] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:46 +0530] [83327] [INFO] Worker exiting (pid: 83327)
[2024-12-29 21:14:46 +0530] [83506] [INFO] Booting worker with pid: 83506
[2024-12-29 21:14:46 +0530] [83303] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:14:46 +0530] [83303] [INFO] Worker exiting (pid: 83303)
[2024-12-29 21:14:46 +0530] [83507] [INFO] Booting worker with pid: 83507
[2024-12-29 21:14:46 +0530] [83509] [INFO] Booting worker with pid: 83509
[2024-12-29 21:15:22 +0530] [83506] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:22 +0530] [83506] [INFO] Worker exiting (pid: 83506)
[2024-12-29 21:15:22 +0530] [83507] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:22 +0530] [83507] [INFO] Worker exiting (pid: 83507)
[2024-12-29 21:15:22 +0530] [83509] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:22 +0530] [83509] [INFO] Worker exiting (pid: 83509)
[2024-12-29 21:15:22 +0530] [83618] [INFO] Booting worker with pid: 83618
[2024-12-29 21:15:22 +0530] [83619] [INFO] Booting worker with pid: 83619
[2024-12-29 21:15:22 +0530] [83415] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:22 +0530] [83415] [INFO] Worker exiting (pid: 83415)
[2024-12-29 21:15:22 +0530] [83633] [INFO] Booting worker with pid: 83633
[2024-12-29 21:15:22 +0530] [83645] [INFO] Booting worker with pid: 83645
[2024-12-29 21:15:22 +0530] [83428] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:22 +0530] [83428] [INFO] Worker exiting (pid: 83428)
[2024-12-29 21:15:22 +0530] [83430] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:22 +0530] [83430] [INFO] Worker exiting (pid: 83430)
[2024-12-29 21:15:23 +0530] [83427] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:23 +0530] [83427] [INFO] Worker exiting (pid: 83427)
[2024-12-29 21:15:23 +0530] [83671] [INFO] Booting worker with pid: 83671
[2024-12-29 21:15:23 +0530] [83431] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:23 +0530] [83431] [INFO] Worker exiting (pid: 83431)
[2024-12-29 21:15:23 +0530] [83673] [INFO] Booting worker with pid: 83673
[2024-12-29 21:15:23 +0530] [83467] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:23 +0530] [83467] [INFO] Worker exiting (pid: 83467)
[2024-12-29 21:15:23 +0530] [83454] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:15:23 +0530] [83454] [INFO] Worker exiting (pid: 83454)
[2024-12-29 21:15:23 +0530] [83690] [INFO] Booting worker with pid: 83690
[2024-12-29 21:15:23 +0530] [83703] [INFO] Booting worker with pid: 83703
[2024-12-29 21:15:23 +0530] [83704] [INFO] Booting worker with pid: 83704
[2024-12-29 21:15:23 +0530] [83706] [INFO] Booting worker with pid: 83706
[2024-12-29 21:17:00 +0530] [83673] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83671] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83671] [INFO] Worker exiting (pid: 83671)
[2024-12-29 21:17:00 +0530] [83673] [INFO] Worker exiting (pid: 83673)
[2024-12-29 21:17:00 +0530] [83704] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83690] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83706] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83706] [INFO] Worker exiting (pid: 83706)
[2024-12-29 21:17:00 +0530] [83690] [INFO] Worker exiting (pid: 83690)
[2024-12-29 21:17:00 +0530] [83704] [INFO] Worker exiting (pid: 83704)
[2024-12-29 21:17:00 +0530] [83703] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83703] [INFO] Worker exiting (pid: 83703)
[2024-12-29 21:17:00 +0530] [84241] [INFO] Booting worker with pid: 84241
[2024-12-29 21:17:00 +0530] [84242] [INFO] Booting worker with pid: 84242
[2024-12-29 21:17:00 +0530] [83618] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83618] [INFO] Worker exiting (pid: 83618)
[2024-12-29 21:17:00 +0530] [84244] [INFO] Booting worker with pid: 84244
[2024-12-29 21:17:00 +0530] [83619] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83619] [INFO] Worker exiting (pid: 83619)
[2024-12-29 21:17:00 +0530] [84268] [INFO] Booting worker with pid: 84268
[2024-12-29 21:17:00 +0530] [84269] [INFO] Booting worker with pid: 84269
[2024-12-29 21:17:00 +0530] [83633] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83633] [INFO] Worker exiting (pid: 83633)
[2024-12-29 21:17:00 +0530] [84281] [INFO] Booting worker with pid: 84281
[2024-12-29 21:17:00 +0530] [83645] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:00 +0530] [83645] [INFO] Worker exiting (pid: 83645)
[2024-12-29 21:17:00 +0530] [84284] [INFO] Booting worker with pid: 84284
[2024-12-29 21:17:01 +0530] [84307] [INFO] Booting worker with pid: 84307
[2024-12-29 21:17:01 +0530] [84308] [INFO] Booting worker with pid: 84308
[2024-12-29 21:17:01 +0530] [84342] [INFO] Booting worker with pid: 84342
[2024-12-29 21:17:25 +0530] [84268] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84268] [INFO] Worker exiting (pid: 84268)
[2024-12-29 21:17:25 +0530] [84244] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84244] [INFO] Worker exiting (pid: 84244)
[2024-12-29 21:17:25 +0530] [84242] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84242] [INFO] Worker exiting (pid: 84242)
[2024-12-29 21:17:25 +0530] [84284] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84284] [INFO] Worker exiting (pid: 84284)
[2024-12-29 21:17:25 +0530] [84269] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84269] [INFO] Worker exiting (pid: 84269)
[2024-12-29 21:17:25 +0530] [84307] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84307] [INFO] Worker exiting (pid: 84307)
[2024-12-29 21:17:25 +0530] [84281] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84281] [INFO] Worker exiting (pid: 84281)
[2024-12-29 21:17:25 +0530] [84393] [INFO] Booting worker with pid: 84393
[2024-12-29 21:17:25 +0530] [84308] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84308] [INFO] Worker exiting (pid: 84308)
[2024-12-29 21:17:25 +0530] [84394] [INFO] Booting worker with pid: 84394
[2024-12-29 21:17:25 +0530] [84396] [INFO] Booting worker with pid: 84396
[2024-12-29 21:17:25 +0530] [84342] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:25 +0530] [84342] [INFO] Worker exiting (pid: 84342)
[2024-12-29 21:17:25 +0530] [84399] [INFO] Booting worker with pid: 84399
[2024-12-29 21:17:26 +0530] [84401] [INFO] Booting worker with pid: 84401
[2024-12-29 21:17:26 +0530] [84403] [INFO] Booting worker with pid: 84403
[2024-12-29 21:17:26 +0530] [84405] [INFO] Booting worker with pid: 84405
[2024-12-29 21:17:26 +0530] [84407] [INFO] Booting worker with pid: 84407
[2024-12-29 21:17:26 +0530] [84409] [INFO] Booting worker with pid: 84409
[2024-12-29 21:17:26 +0530] [84241] [INFO] Worker reloading: /home/malhar/User_Drive/Projects/cn_ddos_protection_python/webserver/rate_limiter.py modified
[2024-12-29 21:17:26 +0530] [84241] [INFO] Worker exiting (pid: 84241)
[2024-12-29 21:17:26 +0530] [84412] [INFO] Booting worker with pid: 84412
[2024-12-29 22:21:21 +0530] [84405] [INFO] Worker exiting (pid: 84405)
[2024-12-29 22:21:21 +0530] [84407] [INFO] Worker exiting (pid: 84407)
[2024-12-29 22:21:21 +0530] [84394] [INFO] Worker exiting (pid: 84394)
[2024-12-29 22:21:21 +0530] [84393] [INFO] Worker exiting (pid: 84393)
[2024-12-29 22:21:21 +0530] [84401] [INFO] Worker exiting (pid: 84401)
[2024-12-29 22:21:21 +0530] [84396] [INFO] Worker exiting (pid: 84396)
[2024-12-29 22:21:21 +0530] [84412] [INFO] Worker exiting (pid: 84412)
[2024-12-29 22:21:21 +0530] [84409] [INFO] Worker exiting (pid: 84409)
[2024-12-29 22:21:21 +0530] [84399] [INFO] Worker exiting (pid: 84399)
[2024-12-29 22:21:21 +0530] [84403] [INFO] Worker exiting (pid: 84403)
[2024-12-29 22:21:21 +0530] [82489] [INFO] Handling signal: term
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84401) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84403) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84405) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84393) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84412) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84396) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84394) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84399) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84407) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [ERROR] Worker (pid:84409) was sent SIGTERM!
[2024-12-29 22:21:21 +0530] [82489] [INFO] Shutting down: Master
